---
- hosts: localhost
  tasks:
  ###############
  #
  # basic
  #
  ###############
  - name: Set up authorized_keys for the root user
    authorized_key: user=root
                    key="{{ lookup('file', item) }}"
    with_fileglob:
      - authorized_keys/*

  - name: Setup Ansible local cron job
    cron: name=ansible_timed minute=*/30 job="cd /vagrant && ansible-playbook -i localhost.yml playbook.yml"

  ###############
  #
  # python
  #
  ###############
  - name: python
    apt: name=python-pip state=latest
  - name: docker-py
    pip: name=docker-py

  ###############
  #
  # docker
  #
  ###############
  - name: docker apt keys
    apt_key: url=http://get.docker.io/gpg id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present
  - name: docker apt repo
    apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
  - name: docker latest
    apt: pkg=lxc-docker state=latest
  - name: docker service
    service: name=docker enabled=true state=started

  ###############
  #
  # minecraft
  #
  ###############
  - name: minecraft
    docker: image=itzg/minecraft-server name=minecraft env="JVM_OPTS=-Xmx2048M -Xms2048M,MOTD=Baddogs Server,EULA=TRUE" ports="25565:25565" volumes=/vagrant/minecraft:/data:rw

  ###############
  #
  # minecraft www
  #
  ###############
  - name: minecraft-www
    docker: image=nginx name=minecraft-www ports=80:80 volumes=/vagrant/minecraft-www:/usr/share/nginx/html:ro

  ###############
  #
  # minecraft maps
  #
  ###############
  - name: minecraft-map cron job
    cron: name=minecraft-map minute=0 hour=8 job="docker run -c 256 --rm -v /vagrant/minecraft:/minecraft:ro -v /vagrant/minecraft-www:/www ianneub/minecraft-map-generator && rm /vagrant/minecraft-www/markers*; docker run -c 256 --rm -v /vagrant/minecraft:/minecraft:ro -v /vagrant/minecraft-www:/www ianneub/minecraft-map-generator --genpoi"
